on:
  push:
    branches:
      - 'master'
    paths:
      - 'packer/vagrant/template_win-8.json'
      - 'packer/vagrant/scripts/windows/**'

jobs:
  build:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Build Vagrant Installer Boxes (windows)
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Build Box
        run: ./.ci/build-boxes.sh
        working-directory: ${{github.workspace}}
        env:
          PKT_PACKER_BUILDS="win-8"
      - name: Clean Workspace
        if: always()
        run: rm -rf ${{ github.workspace }}
